import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import { Toaster } from "sonner"; // ✅ 追加

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-noto-sans-jp",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="dark">
      <body
        className={`${notoSansJP.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased bg-dot bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-black`}
      >
        <Header isMobile={false} currentPage="" />
        {children}
        <Toaster richColors position="top-center" /> {/* ✅ 追加ここ */}
      </body>
    </html>
  );
}
